Repository rackerlabs/docs-developer-blog, pull requests merged in 2020-05, with the labels that each got.

#777 long-running backups
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture1.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture10.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture2.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture3.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture4.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture5.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture6.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture7.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture8.png
  _assets/img/2020-05-01-create-alerts-for-long-running-backups-on-Azure/Picture9.png
  _posts/2020-05-01-create-alerts-for-long-running-backups-on-Azure.md
Labels: CFA - covid19

#778 vs code config
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture1.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture10.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture11.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture12.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture2.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture3.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture4.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture5.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture6.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture7.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture8.png
  _assets/img/2020-05-02-configure-vs-code-for-azure-and-terraform/Picture9.png
  _posts/2020-05-02-configure-vs-code-for-azure-and-terraform.md
Labels: CFA - covid19

#779 rackconnect global
  _posts/2020-05-04-link-secure-and-optimize-distributed-it-environments-and-workplaces-with-the-rackspace-network-backbone.md
Labels: CFA - covid19

#785 Redis CLI post
  _assets/img/2020-05-11-top-ten-redis-cli-commands/Picture1.png
  _posts/2020-05-11-top-ten-redis-cli-commands.md
Labels: ready to build

#784 mailer post
  _assets/img/2020-05-08-dba-tips-for-handling-workflow-mailer-issues/Picture1.png
  _assets/img/2020-05-08-dba-tips-for-handling-workflow-mailer-issues/Picture2.png
  _assets/img/2020-05-08-dba-tips-for-handling-workflow-mailer-issues/Picture3.png
  _posts/2020-05-08-dba-tips-for-handling-workflow-mailer-issues.md
Labels: ready to build

#783 DDoS post
  _posts/2020-05-06-ddos-protection-for-applications-in-a-data-center.md
Labels: CFA - covid19, ready to build

#793 Editorial changes
  _posts/2020-05-06-ddos-protection-for-applications-in-a-data-center.md
Labels: ready to publish

#795 Editorial changes
  _posts/2020-05-08-dba-tips-for-handling-workflow-mailer-issues.md
Labels: ready to build

#790 Salesforce adoption
  _assets/img/2020-05-12-four-ways-salesforce-admins-can-advocate-for-salesforce-adoption/photo1.png
  _assets/img/2020-05-12-similarities-and-differences-between-salesforce-marketing-cloud-and-pardot/photo1.png
  _posts/2020-05-12-four-ways-salesforce-admins-can-advocate-for-salesforce-adoption.md
  _posts/2020-05-12-similarities-and-differences-between-salesforce-marketing-cloud-and-pardot.md
Labels: ready to publish

#803 top five search
  _assets/img/2020-05-18-top-five-elasticsearch-use-cases/Picture1.png
  _posts/2020-05-18-top-five-elasticsearch-use-cases.md
Labels: editor review

#807 cns for aws
  _posts/2020-03-31-how-rackspace-can-help-transform-your-business-with-machine-learning-and-artificial-intelligence.md
  _posts/2020-04-16-cloud-native-security-for-aws-comes-to-rackspace.md
  _posts/2020-05-08-rackspace-offers-data-modernization.md
  _posts/2020-05-22-cloud-native-scurity-for-aws.md
  bioinfo.txt
Labels: author/sme review

#814 oci post
  _posts/2020-05-26-oci-for-disaster-recovery-and-non-production-instances.md
Labels: author/sme review

#818 dns round-robin
  _assets/img/2020-05-27-glibc-linux-dns-round-robin-explanation/Picture1.png
  _posts/2020-05-27-glibc-linux-dns-round-robin-explanation.md
  bioinfo.txt
Labels: author/sme review

#815 IT auto
  _assets/img/2020-05-27-business-process-automation-saves-the-day/Picture1.png
  _assets/img/2020-05-27-business-process-automation-saves-the-day/Picture2.png
  _assets/img/2020-05-27-business-process-automation-saves-the-day/Picture3.png
  _assets/img/2020-05-27-business-process-automation-saves-the-day/Picture4.png
  _posts/2020-05-27-business-process-automation-saves-the-day.md
Labels: author/sme review

#819 wvd post
  _assets/img/2020-05-28-using-wvd-and-fslogix-part1-and-2/Picture1.png
  _assets/img/2020-05-28-using-wvd-and-fslogix-part1-and-2/Picture2.png
  _assets/img/2020-05-28-using-wvd-and-fslogix-part1-and-2/Picture3.png
  _assets/img/2020-05-28-using-wvd-and-fslogix-part1-and-2/Picture4.png
  _assets/img/2020-05-28-using-wvd-and-fslogix-part1-and-2/Picture5.png
  _posts/2020-05-28-using-wvd-and-fslogix-part1.md
  _posts/2020-05-28-using-wvd-and-fslogix-part2.md
  _posts/2020-05-28-using-wvd-and-fslogix-part3.md
Labels: author/sme review

#823 external tables
  _assets/img/2020-05-28-use-oracle-external-tables/Picture1.png
  _posts/2020-05-28-use-oracle-external-tables.md
Labels: editor review

#813 repub dynamics365 (after pulling the trigger too early)
  _posts/2020-05-29-better-together-dynamics-365-and-microsoft-365.md
Labels: delay publish
