Repository rackerlabs/docs-developer-blog, pull requests merged in 2020-06, with the labels that each got.

#824 leakproof post
  _posts/2020-06-01-are-you-leakproof.md
Labels: editor review

#827 cloudflare
  _posts/2020-06-02-accelerate-and-secure-your-website-with-rackspace-and-cloudflare.md
Labels: author/sme review

#826 Oracle CX Commerce
  _posts/2020-06-03-rackspace-offers-a-compete-suite-of-services-for-oracle-cx-commerce.md
  bioinfo.txt
Labels: delay publish

#828 Mulesoft PLAC
  _assets/img/2020-06-02-mulesoft-integration-and-api-platform-an-introduction/Picture1.png
  _posts/2020-06-02-mulesoft-integration-and-api-platform-an-introduction.md
  bioinfo.txt
Labels: delay publish

#829 operational readiness
  _posts/2020-06-04-do-you-have-an-operatoinal-readiness-checklist.md
Labels: editor review

#842 Database
  _posts/2020-06-22-rackspace-now-offers-database-migration-services.md
Labels: review: editor

#847 EA snapshotting
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture1.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture10.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture11.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture2.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture3.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture4.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture5.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture6.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture7.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture8.png
  _assets/img/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data/Picture9.png
  _posts/2020-06-29-einstein-analytics-snapshotting-find-trends-and-patterns-in-your-data.md
  bioinfo.txt
Labels: review: author/sme
